#========================================
# General settings
#========================================
spring:
  application:
    name: api-education-finder
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  cache:
    cache-names:
      - course-filters
      - subject-filters
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=86400s
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
