#========================================
# Test profile settings (junit tests)
#========================================
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:sqlserver:2019-CU28-ubuntu-20.04:///
  sql:
    init:
      data-locations: classpath:db/schema.sql, classpath:db/scripts/testdata.sql
      encoding: utf-8
      mode: always
  cache:
    type: none
logging:
  level:
    root: INFO
